name: Prerelease assets

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build prerelease assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Get current datetime
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d-%H%M%S')"

      - name: Build
        run: ./release.sh ${{ steps.date.outputs.date }}

      # https://github.com/svenstaro/upload-release-action
      - name: Upload release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.date.outputs.date }}
          file: ./release/*
          file_glob: true
          overwrite: true
          prerelease: true
          body: "This is an untested version. Use at your own risk."
