name: Release assets

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Display the commit
        run: echo ${{ github.sha }}

      - name: Build
        run: ./release.sh ${{ github.sha }}

      # https://github.com/svenstaro/upload-release-action
      - name: Upload release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.sha }}
          file: ./release/*
          file_glob: true
          overwrite: true
          prerelease: true
          body: "This is an untested version. Use at your own risk."
